bands:
    b1:
        tag: 多光谱
        order: 1
        resolution: 10
        wavelength: [0.50, 0.59]
        description: Green
    b2:
        tag: 多光谱
        order: 2
        resolution: 10
        wavelength: [0.61, 0.68]
        description: Red
    b3:
        tag: 多光谱
        order: 3
        resolution: 10
        wavelength: [0.78, 0.89]
        description: NIR
    b4:
        tag: 多光谱
        order: 4
        resolution: 10
        wavelength: [1.58, 1.75]
        description: MWIR
    b5:
        tag: 全色
        order: 5
        resolution: 5
        wavelength: [0.48, 0.71]
        description: PAN
    b5:
        tag: 全色
        order: 5
        resolution: 2.5
        wavelength: [0.48, 0.71]
        description: SRPAN
