bands:
    b1:
        tag: 多光谱
        order: 1
        resolution: 73
        wavelength: [0.45, 0.52]
        description: Blue
    b2:
        tag: 多光谱
        order: 2
        resolution: 73
        wavelength: [0.52, 0.59]
        description: Green
    b3:
        tag: 多光谱
        order: 3
        resolution: 73
        wavelength: [0.63, 0.69]
        description: Red
    b4:
        tag: 多光谱
        order: 4
        resolution: 73
        wavelength: [0.77, 0.89]
        description: NIR
