bands:
    b1:
        tag: 全色
        order: 1
        resolution: 2
        wavelength: [0.45, 0.90]
        description: PAN
    b2:
        tag: 多光谱
        order: 2
        resolution: 8
        wavelength: [0.45, 0.52]
        description: Blue
    b3:
        tag: 多光谱
        order: 3
        resolution: 8
        wavelength: [0.52, 0.60]
        description: Green
    b4:
        tag: 多光谱
        order: 4
        resolution: 8
        wavelength: [0.63, 0.69]
        description: Red
    b5:
        tag: 多光谱
        order: 5
        resolution: 8
        wavelength: [0.76, 0.90]
        description: NIR
