bands:
    b1:
        tag: 多光谱
        order: 1
        resolution:
        wavelength:
        description: Red
    b2:
        tag: 多光谱
        order: 2
        resolution:
        wavelength:
        description: Green
    b3:
        tag: 多光谱
        order: 3
        resolution:
        wavelength:
        description: Blue
