bands:
    b1:
        tag: 多光谱
        order: 1
        resolution: 16
        wavelength: [0.45, 0.52]
        description: Blue
        gain: 0.1709
        bias: -0.0039
        BMSI: 1969.7
    b2:
        tag: 多光谱
        order: 2
        resolution: 16
        wavelength: [0.52, 0.59]
        description: Green
        gain: 0.1398
        bias: -0.0047
        BMSI: 1859.7
    b3:
        tag: 多光谱
        order: 3
        resolution: 16
        wavelength: [0.63, 0.69]
        description: Red
        gain: 0.1195
        bias: -0.030
        BMSI: 1560.1
    b4:
        tag: 多光谱
        order: 4
        resolution: 16
        wavelength: [0.77, 0.89]
        description: Near infrared
        gain: 0.1338
        bias: -0.0274
        BMSI: 1078.1
